### ISSUE TITLE
PHP 7 and Object as reserved name

### ISSUE THREAD

**Issue by graste** [honeybee/trellis#13]
See http://php.net/manual/de/migration70.incompatible.php#migration70.incompatible.other.classes – The words `resource`, `object` etc. are not yet a problem, but are reserved for future use. As we use `Object` we should probably react to it now instead of getting into trouble in all projects using trellis later on when php 7.1 or whatever shows up with that breaking change.

While we're at it, we might think about getting rid of the `Object` class altogether.

**Comment by MrHash** [comment]
One option is to rename `Object` to `Trellis` for a quick win

**Comment by graste** [comment]
`BaseObject` was used quite some time ago. Closing this. :)
