### ISSUE TITLE
BC: fix PHP 7.2 compatibility

### ISSUE THREAD

**Issue by graste** [honeybee/trellis#30]
```
PHP Fatal error:  Cannot use Trellis\Common\Object as Object because 'Object' is a special class name in…
```

We can't use `Object` as a class name anymore. Was to be expected since some time and now we can't skip this change any longer. I suggest we think about whether we simply rename the class and then in a second step check whether there are classes that don't need to extend Object anymore.

**Comment by Pictor13** [comment]
What about the new name?

```DataObject```?
```BaseObject```?
```DataSet```?
```Thing```?
```StateHolder```? (brrrhh 😖)
```Arrayable``` / ```Dumpable``` / ```Serializable``` (according to its interface method)
... other?

**Comment by graste** [comment]
Maybe rename to BaseObject and then remove it as an extended class where possible... What would @shrink0r do?

**Comment by graste** [comment]
meh, forgot to reference this ticket in commit rev b2a4107
 
[master b2a4107] BC break: rename Object to BaseObject for PHP 7.2

Reminder to self: don't try to fix php7.2 compatibility on localhost w/ the php version not being 7.2. :1st_place_medal:

**Comment by graste** [comment]
From tag 0.2.1 on trellis should work on php 7.2 w/o (known) problems.
